import React,{useMemo,useRef,useState}from"react";
import{createRoot}from"react-dom/client";
import{Users,FileText,MessageSquare,Phone,BarChart3,Plug,Settings,Search,Bell,Plus,ChevronLeft,ChevronRight,X,PauseCircle,Send,Mail,Bot,Download,SlidersHorizontal,Columns3,GripVertical,Check,FolderOpen,Sparkles}from"lucide-react";
import"./application.css";

const LEADS=12842,APP_COUNT=Math.round(LEADS*.2);
const counselors=["Vivek Rao","Sneha Kulkarni","Aayush Sharma","Harshitha Reddy"],programs=["PGDM","MBA","B.Tech","BBA","Executive MBA"],specializations=["Finance","Marketing","Business Analytics","Computer Science","HR","Operations"],sources=["Instagram","YouTube","Organic","Meta Lead Ads","Google Ads","Referral","Walk-in","Consultant"],campaigns=["PGDM Retargeting","MBA Search Q3","Engineering Q1","Open Day","Scholarship Drive","Campus Event"],stages=["Application Initiated","In Progress","Documents Pending","Documents Verified","Payment Pending","Payment Completed","Offer Released","Admission Confirmed","Withdrawn"],payments=["Not Started","Pending","Part Paid","Paid"],priorities=["Low","Medium","High"],first=["Sneha","Arjun","Priya","Dev","Neha","Rohit","Meera","Yash","Karthik","Ananya","Vikram","Tanvi"],last=["Rathi","Kumar","Patel","Verma","Kapoor","Singh","Shah","Tiwari","Iyer","Sharma","Reddy","Nair"];
const seeded=i=>{const x=Math.sin(i*12.9898)*43758.5453;return x-Math.floor(x)};
function makeApps(){return Array.from({length:APP_COUNT},(_,n)=>{const id=n+1,f=first[Math.floor(seeded(id)*first.length)],l=last[Math.floor(seeded(id+1)*last.length)],progress=Math.min(100,Math.round(18+seeded(id+2)*82)),docs=Math.min(6,Math.floor(progress/17)),health=Math.min(98,Math.round(progress*.62+seeded(id+3)*35)),payment=progress>88?"Paid":progress>68?"Part Paid":progress>48?"Pending":"Not Started";return{id,name:`${f} ${l}`,leadId:`LEAD-${String(id).padStart(6,"0")}`,applicationId:`APP-${String(id).padStart(6,"0")}`,email:`${f.toLowerCase()}.${l.toLowerCase()}${id%93}@example.com`,phone:`+91 9${String(100000000+Math.floor(seeded(id+4)*899999999)).slice(0,9)}`,program:programs[Math.floor(seeded(id+5)*programs.length)],specialization:specializations[Math.floor(seeded(id+6)*specializations.length)],intake:seeded(id+7)>.5?"Jan 2027":"Jul 2027",stage:stages[Math.min(stages.length-1,Math.floor(progress/12))],progress,fieldsCompleted:Math.round(progress*.29),documents:`${docs}/6`,documentsUploaded:docs,paymentStatus:payment,feePaid:payment==="Paid"?200000:payment==="Part Paid"?50000:0,health,source:sources[Math.floor(seeded(id+8)*sources.length)],campaign:campaigns[Math.floor(seeded(id+9)*campaigns.length)],counselor:counselors[Math.floor(seeded(id+10)*counselors.length)],owner:counselors[Math.floor(seeded(id+11)*counselors.length)],priority:priorities[Math.floor(seeded(id+12)*priorities.length)],city:["Pune","Mumbai","Delhi","Bengaluru","Hyderabad","Jaipur"][Math.floor(seeded(id+13)*6)],state:["Maharashtra","Delhi","Karnataka","Telangana","Rajasthan"][Math.floor(seeded(id+14)*5)],scholarship:seeded(id+15)>.72?"Requested":"No",createdDate:`2026-08-${String(id%5+1).padStart(2,"0")}`,updatedDate:`2026-08-${String(id%5+1).padStart(2,"0")}`,lastActivity:["2 mins ago","15 mins ago","1 hr ago","Yesterday"][Math.floor(seeded(id+16)*4)],lastCall:["Today","Yesterday","3 days ago","Never"][Math.floor(seeded(id+17)*4)],lastWhatsApp:["Today","Yesterday","2 days ago","Never"][Math.floor(seeded(id+18)*4)],parked:false}})}
const baseColumns=[["student","Student"],["applicationId","Application ID"],["program","Program"],["progress","Progress"],["stage","Stage"],["documents","Documents"],["paymentStatus","Payment"],["health","Health"],["source","Source"],["campaign","Campaign"],["counselor","Counselor"],["lastActivity","Last Activity"]];
const filtersList=[["stage","Stage"],["progress","Progress %"],["program","Program"],["specialization","Specialization"],["intake","Intake"],["documentsUploaded","Documents Uploaded"],["paymentStatus","Payment Status"],["feePaid","Fee Paid"],["health","Health Score"],["source","Source"],["campaign","Campaign"],["counselor","Counselor"],["owner","Owner"],["priority","Priority"],["city","City"],["state","State"],["scholarship","Scholarship"],["createdDate","Created Date"],["updatedDate","Updated Date"],["lastActivity","Last Activity"],["lastCall","Last Call"],["lastWhatsApp","Last WhatsApp"]];
const nav=[["leads","Lead Manager",Users],["applications","Application Manager",FileText],["communications","Communications",MessageSquare],["calling","AI Calling",Phone],["analytics","Reports & Analytics",BarChart3],["integrations","Integrations",Plug],["settings","Settings",Settings]];

function App(){
const[apps,setApps]=useState(makeApps),[query,setQuery]=useState(""),[selectedId,setSelectedId]=useState(1),[drawerOpen,setDrawerOpen]=useState(true),[drawerWidth,setDrawerWidth]=useState(640),[tab,setTab]=useState("Overview"),[filters,setFilters]=useState([]),[filterOpen,setFilterOpen]=useState(false),[columnsOpen,setColumnsOpen]=useState(false),[columns,setColumns]=useState(baseColumns),[hidden,setHidden]=useState(new Set),[view,setView]=useState("All Applications"),[selectedRows,setSelectedRows]=useState(new Set),[page,setPage]=useState(1),[toast,setToast]=useState("");
const resize=useRef(false),drag=useRef(null),pageSize=25;
React.useEffect(()=>{const move=e=>{if(!resize.current)return;setDrawerWidth(Math.min(innerWidth-90,Math.max(420,innerWidth-e.clientX-10)))};const up=()=>{resize.current=false;document.body.style.cursor=""};addEventListener("mousemove",move);addEventListener("mouseup",up);return()=>{removeEventListener("mousemove",move);removeEventListener("mouseup",up)}},[]);
const filtered=useMemo(()=>apps.filter(a=>{const text=[a.name,a.email,a.phone,a.applicationId,a.leadId].join(" ").toLowerCase();if(query&&!text.includes(query.toLowerCase()))return false;return filters.every(f=>{const v=a[f.key];if(f.operator==="equals")return String(v)===String(f.value);if(f.operator==="contains")return String(v).toLowerCase().includes(String(f.value).toLowerCase());if(f.operator==="gt")return Number(v)>Number(f.value);if(f.operator==="lt")return Number(v)<Number(f.value);return true})}),[apps,query,filters]);
const selected=apps.find(a=>a.id===selectedId)||apps[0],selectedIndex=filtered.findIndex(a=>a.id===selected.id),pages=Math.max(1,Math.ceil(filtered.length/pageSize)),rows=filtered.slice((page-1)*pageSize,page*pageSize);
const stats=useMemo(()=>({submitted:apps.filter(a=>a.progress>=60).length,inProgress:apps.filter(a=>a.progress<60).length,payment:apps.filter(a=>["Pending","Part Paid"].includes(a.paymentStatus)).length,offer:apps.filter(a=>["Offer Released","Admission Confirmed"].includes(a.stage)).length,avg:Math.round(apps.reduce((s,a)=>s+a.progress,0)/apps.length)}),[apps]);
const notify=m=>{setToast(m);setTimeout(()=>setToast(""),1500)},addFilter=key=>{const label=filtersList.find(x=>x[0]===key)?.[1]||key,num=["progress","health","documentsUploaded","feePaid"].includes(key);setFilters(f=>[...f,{id:Date.now(),key,label,operator:num?"gt":"equals",value:num?50:""}])},updateFilter=(id,p)=>setFilters(f=>f.map(x=>x.id===id?{...x,...p}:x)),removeFilter=id=>setFilters(f=>f.filter(x=>x.id!==id));
const moveColumn=target=>{const source=drag.current;if(!source||source===target)return;setColumns(c=>{const n=[...c],from=n.findIndex(x=>x[0]===source),to=n.findIndex(x=>x[0]===target),[m]=n.splice(from,1);n.splice(to,0,m);return n})};
const change=d=>{if(!filtered.length)return;const next=Math.max(0,Math.min(filtered.length-1,selectedIndex+d));setSelectedId(filtered[next].id)};
return <div className="app-shell"><aside className="sidebar"><div className="brand"><span>E</span><b>ExtraaEdge</b></div>{nav.map(([id,label,Icon])=><button key={id} className={id==="applications"?"active":""} onClick={()=>{if(id==="leads"){location.hash="";location.reload()}}}><Icon size={18}/><span>{label}</span></button>)}</aside>
<main className="main" style={{marginRight:drawerOpen?drawerWidth+10:0}}><header className="topbar"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, email, mobile, application ID..."/></div><button><Bell size={18}/></button><button className="primary"><Plus size={16}/>Add</button></header><section className="workspace"><div className="kpi-grid"><Kpi label="Total Leads" value={LEADS} sub="All leads"/><Kpi label="Applications (20%)" value={APP_COUNT} sub="20% of total leads"/><Kpi label="Applications Submitted" value={stats.submitted} sub={`${stats.submitted} leads · ${stats.submitted} apps`}/><Kpi label="In Progress" value={stats.inProgress} sub={`${stats.inProgress} leads · ${stats.inProgress} apps`}/><Kpi label="Payment Pending" value={stats.payment} sub={`Average progress ${stats.avg}%`}/><Kpi label="Offer / Admission" value={stats.offer} sub="Converted applications"/></div>
<div className="application-toolbar"><div className="views">{["All Applications","My Applications","Pending Documents","Payment Pending","High Progress","Scholarship Cases"].map(v=><button key={v} className={view===v?"active":""} onClick={()=>setView(v)}>{v}</button>)}</div><div className="toolbar-actions"><button onClick={()=>setFilterOpen(v=>!v)}><SlidersHorizontal size={15}/>Add Filter</button><button onClick={()=>setColumnsOpen(v=>!v)}><Columns3 size={15}/>Columns</button><button><Download size={15}/>Export</button></div></div>
{filterOpen&&<div className="filter-builder"><div className="filter-catalog">{filtersList.map(([key,label])=><button key={key} onClick={()=>addFilter(key)}><Plus size={13}/>{label}</button>)}</div></div>}{filters.length>0&&<div className="filter-chips">{filters.map(f=><div className="filter-chip" key={f.id}><b>{f.label}</b><select value={f.operator} onChange={e=>updateFilter(f.id,{operator:e.target.value})}><option value="equals">equals</option><option value="contains">contains</option><option value="gt">greater than</option><option value="lt">less than</option></select><input value={f.value} onChange={e=>updateFilter(f.id,{value:e.target.value})}/><button onClick={()=>removeFilter(f.id)}><X size={13}/></button></div>)}</div>}
{columnsOpen&&<div className="columns-panel"><h4>Customise columns</h4><p>Show, hide and drag columns.</p>{columns.map(([key,label])=><div key={key} draggable onDragStart={()=>drag.current=key} onDragOver={e=>e.preventDefault()} onDrop={()=>moveColumn(key)}><GripVertical size={15}/><label><input type="checkbox" checked={!hidden.has(key)} onChange={()=>setHidden(h=>{const n=new Set(h);n.has(key)?n.delete(key):n.add(key);return n})}/>{label}</label></div>)}</div>}
<div className="table-card"><div className="bulk-bar"><b>{selectedRows.size}</b> selected<button onClick={()=>notify("Counselor assignment opened")}>Assign Counselor</button><button><Send size={14}/>WhatsApp</button><button><Mail size={14}/>Email</button><button><Bot size={14}/>AI Call</button><button><FolderOpen size={14}/>Request Documents</button></div><div className="table-wrap"><table><thead><tr><th><input type="checkbox" checked={rows.length>0&&rows.every(r=>selectedRows.has(r.id))} onChange={e=>setSelectedRows(e.target.checked?new Set(rows.map(r=>r.id)):new Set)}/></th>{columns.filter(([k])=>!hidden.has(k)).map(([k,l])=><th key={k} draggable onDragStart={()=>drag.current=k} onDragOver={e=>e.preventDefault()} onDrop={()=>moveColumn(k)}>{l}</th>)}</tr></thead><tbody>{rows.map(a=><tr key={a.id} className={selected.id===a.id?"selected":""} onClick={()=>{setSelectedId(a.id);setDrawerOpen(true)}}><td onClick={e=>e.stopPropagation()}><input type="checkbox" checked={selectedRows.has(a.id)} onChange={()=>setSelectedRows(s=>{const n=new Set(s);n.has(a.id)?n.delete(a.id):n.add(a.id);return n})}/></td>{columns.filter(([k])=>!hidden.has(k)).map(([k])=><td key={k}>{cell(k,a)}</td>)}</tr>)}</tbody></table></div><div className="pagination"><span>Showing {(page-1)*pageSize+1}–{Math.min(page*pageSize,filtered.length)} of {filtered.length.toLocaleString("en-IN")}</span><button disabled={page===1} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={15}/></button><span>{page} / {pages}</span><button disabled={page===pages} onClick={()=>setPage(p=>p+1)}><ChevronRight size={15}/></button></div></div></section></main>
{drawerOpen&&<aside className="drawer" style={{width:drawerWidth}}><div className="resize-handle" onMouseDown={()=>{resize.current=true;document.body.style.cursor="col-resize"}}/><div className="drawer-header"><h2>Application 360</h2><div className="record-nav"><button disabled={selectedIndex<=0} onClick={()=>change(-1)}><ChevronLeft size={15}/>Previous</button><span>{selectedIndex+1} of {filtered.length.toLocaleString("en-IN")}</span><button disabled={selectedIndex>=filtered.length-1} onClick={()=>change(1)}>Next<ChevronRight size={15}/></button></div><button className="park" onClick={()=>{setApps(x=>x.map(a=>a.id===selected.id?{...a,parked:!a.parked}:a));notify(selected.parked?"Application unparked":"Application parked")}}><PauseCircle size={15}/>{selected.parked?"Unpark":"Park Application"}</button><button className="close" onClick={()=>setDrawerOpen(false)}><X size={18}/></button></div><div className="profile"><div className="avatar">{selected.name.split(" ").map(x=>x[0]).join("")}</div><div><h3>{selected.name}</h3><p>{selected.applicationId} · {selected.phone}</p><p>{selected.email}</p></div><div className="score"><span>Health</span><b>{selected.health}</b></div></div><div className="quick-actions"><button><Phone size={16}/>Call</button><button><Send size={16}/>WhatsApp</button><button><Mail size={16}/>Email</button><button><MessageSquare size={16}/>SMS</button><button><Bot size={16}/>AI Call</button></div><div className="drawer-tabs">{["Overview","Timeline","Documents","Payments","Communications","Notes","AI Summary"].map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t}</button>)}</div><div className="drawer-body">{tab==="Overview"?<Overview app={selected}/>:<Tab tab={tab} app={selected}/>}</div></aside>}{toast&&<div className="toast">{toast}</div>}</div>}
function Kpi({label,value,sub}){return <div className="kpi"><span>{label}</span><b>{value.toLocaleString("en-IN")}</b><small>{sub}</small></div>}
function cell(k,a){if(k==="student")return <div className="student-cell"><span>{a.name.split(" ").map(x=>x[0]).join("")}</span><div><b>{a.name}</b><small>{a.leadId}</small></div></div>;if(k==="progress")return <div className="progress-cell"><div><b>{a.progress}%</b><small>{a.fieldsCompleted}/29 fields</small></div><span><i style={{width:`${a.progress}%`}}/></span></div>;if(k==="health")return <div className={`health ${a.health>=75?"good":a.health>=50?"mid":"low"}`}><Sparkles size={13}/>{a.health}</div>;if(k==="program")return <><b>{a.program}</b><small>{a.specialization} · {a.intake}</small></>;if(k==="stage")return <span className="stage">{a.stage}</span>;if(k==="paymentStatus")return <><b>{a.paymentStatus}</b><small>₹{a.feePaid.toLocaleString("en-IN")}</small></>;if(k==="source")return <><b>{a.source}</b><small>{a.campaign}</small></>;return <>{String(a[k])}</>}
function Overview({app}){const sections=[["Personal Details",100],["Academic Details",Math.min(100,app.progress+15)],["Address",Math.min(100,app.progress+8)],["Parent Details",Math.min(100,app.progress+3)],["Documents",Math.round(app.documentsUploaded/6*100)],["Payment",app.paymentStatus==="Paid"?100:app.paymentStatus==="Part Paid"?50:app.paymentStatus==="Pending"?20:0],["Declaration",app.progress>90?100:0],["Final Submit",app.progress===100?100:0]];return <><div className="summary-grid"><Info label="Progress" value={`${app.progress}%`}/><Info label="Health" value={`${app.health}/100`}/><Info label="Documents" value={app.documents}/><Info label="Payment" value={app.paymentStatus}/></div><div className="panel"><h4>Application Progress</h4><div className="large-progress"><div><b>{app.progress}% complete</b><span>{app.fieldsCompleted} of 29 fields completed</span></div><span><i style={{width:`${app.progress}%`}}/></span></div><div className="section-progress">{sections.map(([l,v])=><div key={l}><span>{v===100?<Check size={14}/>:<span className="dot"/>}</span><div><b>{l}</b><small>{v}% complete</small></div></div>)}</div></div><div className="panel"><h4>Application Details</h4><div className="detail-grid"><Info label="Program" value={`${app.program} (${app.specialization})`}/><Info label="Intake" value={app.intake}/><Info label="Source" value={app.source}/><Info label="Campaign" value={app.campaign}/><Info label="Counselor" value={app.counselor}/><Info label="Owner" value={app.owner}/></div></div><div className="panel"><h4>AI Next Action</h4><p>{app.progress<50?"Guide the aspirant to complete personal and academic details.":app.documentsUploaded<6?"Request pending documents and verify uploaded files.":app.paymentStatus!=="Paid"?"Send payment reminder and arrange counselor follow-up.":"Prepare offer and admission confirmation workflow."}</p></div></>}
function Tab({tab,app}){const c={Timeline:["Application created","Personal details updated","Documents uploaded","Counselor follow-up"],Documents:["10th Marksheet — Verified","12th Marksheet — Verified","Aadhaar — DigiLocker Verified","Entrance Scorecard — Pending"],Payments:[`Status — ${app.paymentStatus}`,`Paid — ₹${app.feePaid.toLocaleString("en-IN")}`,"Application Fee — ₹2,000"],Communications:["WhatsApp sent — Today","Counselor call — Yesterday","Email opened — 2 days ago"],Notes:["Interested in scholarship and hostel facilities.","Parent callback requested."],"AI Summary":["High likelihood to complete if pending documents and payment are addressed.",`Application health score is ${app.health}/100.`]};return <div className="panel"><h4>{tab}</h4>{(c[tab]||[]).map(x=><div className="list-row" key={x}>{x}</div>)}</div>}
function Info({label,value}){return <div className="info"><span>{label}</span><b>{value}</b></div>}
createRoot(document.getElementById("root")).render(<App/>);